[package]
name = "callgrind2pprof"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["callgrind", "profiling", "performance"]
categories = ["development-tools::profiling"]
description = "Convert Callgrind profiles to pprof"

[dependencies]
callgrind-parser.workspace = true
clap.workspace = true
pprof-profile.workspace = true
