[package]
name = "callgrind-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Parser library for Callgrind profile data"

[lib]
path = "src/lib.rs"

[dependencies]
nom.workspace = true
lasso.workspace = true
smallvec.workspace = true

[dev-dependencies]
proptest.workspace = true
