[package]
name = "textgrind"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Terminal UI for exploring Callgrind profiles"

[dependencies]
callgrind-parser.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true

[package.metadata.dist]
dist = false
