[package]
name = "pprof2callgrind"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["callgrind", "profiling", "performance"]
categories = ["development-tools::profiling"]
description = "Exact-integer pprof to Callgrind graph and context-tree conversion"

[dependencies]
pprof-profile.workspace = true
callgrind-writer.workspace = true
clap.workspace = true

[dev-dependencies]
callgrind-parser.workspace = true
prost.workspace = true
